name: opus_flutter_mac
description: iOS implementation of the opus_flutter plugin.
repository: https://gitee.com/cs20304/opus_flutter/tree/master/opus_flutter_mac
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  opus_flutter_platform_interface: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/darwin/libopus.dylib
    - assets/darwin_aarch64/libopus.dylib
  plugin:
    implements: opus_flutter
    platforms:
      mac:
        pluginClass: OpusFlutterIosPlugin